### ISSUE TITLE
letsencrypt: HTTPS server bind 0.0.0.0:443 when host=localhost is set

### ISSUE THREAD

**Issue by tpng** [mholt/caddy#309]
In my setup, I was running `sslh` (port multiplexer) on `0.0.0.0:443` to proxy `localhost:443`.
When I start `caddy -host localhost`, following error is returned.
```
2015/11/03 12:53:41 Obtaining certificates...
2015/11/03 12:53:41 Trying to solve SimpleHTTP
[example.com] failed to get certificate: Could not start HTTPS server for challenge -> listen tcp :443: bind: address already in use
```
Expected HTTPS server to bind on localhost:443.

Still, thanks for the great work on adding Let's Encrypt support!

**Comment by mholt** [comment]
Hmm, indeed, Caddy expects that port to be available so it can solve the certificate challenge. Let me experiment locally real quick on a good way to work with this.

**Comment by tpng** [comment]
example.com was just a placeholder for my real domain name, my Caddyfile look like this:
```
realdomainhere.example.com
bind localhost
root public
gzip
```

**Comment by tpng** [comment]
It seems the [acme package bind to 443 or a custom port on 0.0.0.0](https://github.com/xenolf/lego/blob/3e1a5dc04b649b51b0ce2a6742c5295613832382/acme/simple_http_challenge.go#L122).
So we can't bind to the address specified by the `bind` directive without changing the acme package.

**Comment by mholt** [comment]
@tpng I just committed the change upstream. Do you have Go installed? If so, would you pull the latest (both Caddy and xenolf/lego/acme) and try it again? If not, let me know and we'll get you a binary.

**Comment by tpng** [comment]
Just go get'ed the latest Caddy and it now binds to localhost correctly, thanks!

```
2015/11/04 07:57:18 Obtaining certificates...
2015/11/04 07:57:19 Trying to solve SimpleHTTP
2015/11/04 07:57:21 Served JWS payload...
2015/11/04 07:57:21 The server validated our request
2015/11/04 07:57:21 Validations succeeded. Getting certificates
2015/11/04 07:57:22 Requesting issuer cert from: https://acme-staging.api.letsencrypt.org/acme/issuer-cert
2015/11/04 07:57:22 [mydomain.com] Server responded with a certificate.
[INFO] Processing certificate renewals...
mydomain.com:https
Notice: mydomain.com is only accessible on this machine (127.0.0.1)
mydomain.com:http
```

**Comment by mholt** [comment]
Yay :tada: Thanks for the report!

**Comment by abh** [comment]
This seems like it broke again in 0.8.1.

All my http{s}://... sections include an import of "common.conf" which in turn has "bind 10.0.0.1"; however it still fails on startup with `failed to get certificate: Could not start HTTP server for challenge -> listen tcp :80: bind: address already in use`.

**Comment by mholt** [comment]
Oops. There was a recent change in lego that changes how the listen addresses were specified, let me look into this.

**Comment by abh** [comment]
Cool, thank you. :-)

**Comment by mholt** [comment]
@abh Unfortunately, this change will break in certain scenarios -- I've already seen this on DigitalOcean, for instance -- where the hostname is in the /etc/hosts file, so it resolves back to 127.0.0.1. In other words, a droplet whose hostname is example.com will not successfully complete the ACME challenge if I make this change.

**Comment by abh** [comment]
I only ever looked briefly at the lego API, but I think maybe some of this is because the APIs there are doing too much in one.

The calling application should have control over which ports to listen on. In the case of caddy it doesn’t make sense for lego to make up its own idea of what to listen on. The Caddy configuration needs to be correct anyway for it to work. Lego second guessing it is unhelpful, no?

if /etc/hosts have example.com pointing to 127.0.0.1 that’s just wrong, too. (And again, if the lego API would just trust what caddy tells it to do it wouldn’t be a problem; I understand that for easy of use the lego program wants to do a bit of guess work).

**Comment by mholt** [comment]
> The calling application should have control over which ports to listen on. In the case of caddy it doesn’t make sense for lego to make up its own idea of what to listen on. The Caddy configuration needs to be correct anyway for it to work. Lego second guessing it is unhelpful, no?

It has control by using [client.SetHTTPAddress](https://godoc.org/github.com/xenolf/lego/acme#Client.SetHTTPAddress) and client.SetTLSAddress - but right now Caddy just uses addresses like ":80" which won't be affected by the local hosts file.

So lego is not being presumptuous -- it's just my conservative approach that is causing the issue.

> if /etc/hosts have example.com pointing to 127.0.0.1 that’s just wrong, too.

I agree, but let me verify that this is not common first. If not, I will look into how to best make the change.

**Comment by abh** [comment]
> On Jan 31, 2016, at 16:00, Matt Holt <notifications@github.com> wrote:
> 
> I agree, but let me verify that this is not common first. If not, I will look into how to best make the change.

Honor any bind statements (do whatever caddy does for the regular listening)?

**Comment by mholt** [comment]
> Honor any bind statements (do whatever caddy does for the regular listening)?

Yeah, we could do that, but I need to work that into the design somehow.

@captncraig was nice enough to check this for me and apparently DigitalOcean still adds the hostname of the droplet to /etc/hosts as 127.0.0.1. This is unfortunate.

I'll need some time to get to this. So... I will re-open the issue until I or somebody implements the fix. All we need to do is use the server.Config.BindAddr field with the acme.Client that is created in the letsencrypt package, the newClientPort function.

**Comment by mholt** [comment]
I've restructured the `letsencrypt` package and renamed it to the `https` package, and I need to restructure yet again to fully implement this change... not an easy change to make.

**Comment by danielsteiner** [comment]
Not sure what the status about this is, but I am currently running Caddy 0.8.3 with all extensions except for JSONP and Hugo on a Windows 10 Server and one Windows 10 Pro (TH2) machine and both give me the following error when running caddy with TLS enabled: 


`Activating privacy features...2016/05/19 11:11:43 [frontend.example.com] failed to get certificate: [frontend.example.com] error presenting token: Could not start HTTPS server for challenge -> listen tcp :443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`

My first guess was that the port 443 is in use but sometimes it tells me the exact same error message but with port 80, also netsat -o says that no port <50k is in use (speak: neither 80 nor 443 are in use) 

here you've got my caddyfile: 

`frontend.example.com {
	gzip
    root wwwroot/frontend/public
    log access.log
    errors error.log
    startup "C:\Program Files (x86)\PHP\v7.0\php-cgi.exe" -b 127.0.0.1:9123 &
    fastcgi / 127.0.0.1:9123 php
    rewrite {
        r .*
        ext /
        to /index.php?{query}
    }
    header / {
	    +Link "</images/image.png>; rel=preload"
	    +Link "</css/main.css>; rel=preload"
	}
}

backend.example.com {
	gzip
    root wwwroot/backend/public
    log access.log
    errors error.log
    startup "C:\Program Files (x86)\PHP\v7.0\php-cgi.exe" -b 127.0.0.1:9123 &
    fastcgi / 127.0.0.1:9123 php
    rewrite {
        r .*
        ext /
        to /index.php?{query}
    }
}

licensing.example.com {
	tls off
	gzip
    root wwwroot/licensing/public
    log access.log
    errors error.log
    startup "C:\Program Files (x86)\PHP\v7.0\php-cgi.exe" -b 127.0.0.1:9123 &
    fastcgi / 127.0.0.1:9123 php
    rewrite {
        r .*
        ext /
        to /index.php?{query}
    }
}
api.example.com {
	gzip
    root wwwroot/backend/public
    log access.log
    errors {
	log error.log {
		size 50 # Rotate after 50 MB
		age  30 # Keep rotated files for 30 days
		keep 5  # Keep at most 5 log files
	}
}
    startup "C:\Program Files (x86)\PHP\v7.0\php-cgi.exe" -b 127.0.0.1:9123 &
    fastcgi / 127.0.0.1:9123 php
    rewrite {
        r .*
        ext /
        to /index.php?{query}
    }
    header / Access-Control-Allow-Origin *
}`

And I'm starting caddy with a bat script: 

`@ECHO OFF
@TITLE Caddy - The HTTP/2 Web Server with Fully Managed SSL
cd C:\inetpub\caddy
caddy.exe -conf=caddy.conf
pause`

**Comment by tpng** [comment]
Try `netstat -ao` and look for those with `LISTENING` status.

**Comment by danielsteiner** [comment]
```
TCP    0.0.0.0:80             cwbsvr1:0               LISTENING       4
TCP    0.0.0.0:443            cwbsvr1:0               LISTENING       4
```

looks like we've got the cause of this.

**Comment by tpng** [comment]
Since you forced kill the process, you may need to wait for a period of time before the sockets are released by Windows.
If you can find out what service it is, try disabling it and restart Windows to see if you can start Caddy.

**Comment by danielsteiner** [comment]
It was IIS. I forgot to turn it off. BTW, on my local machine, the ports were not used. It seems to work now, if I manually specify the ports 443 and 80 to the configs.

**Comment by mholt** [comment]
You will be relieved to know that I think this is fixed in the 0.9 rewrite. If Caddy starts a listener to solve an ACME challenge, it binds to the address/interface specified by the `bind` directive.

Closing since it's fixed locally, you should see the changes roll out with the 0.9 beta versions. If you confirm it is *not* fixed, please re-open this issue and let me know all the juicy details. Thanks!

**Comment by abh** [comment]
Excellent, thank you!

**Comment by mholt** [comment]
You're welcome. This was not an easy fix :smile:
